#!/bin/bash
# CORE-INFRA-REQ-001: TikTok Client Routing Deployment Script
# This script provides the commands for deploying the TikTok routing on VPS
# 
# USAGE: Review each command and execute manually
# DO NOT run this script directly - it is for reference only
#
# Prerequisites:
# - Client service deployed at /opt/flowbiz/clients/flowbiz-client-live-tiktok
# - Gateway API running on 127.0.0.1:3001
# - Dashboard UI running on 127.0.0.1:3002 (private)

echo "================================================================"
echo "STEP 1: Pull latest core repository changes"
echo "================================================================"
echo "cd /opt/flowbiz/flowbiz-ai-core"
echo "git pull origin main"

echo ""
echo "================================================================"
echo "STEP 2: Verify new nginx template exists"
echo "================================================================"
echo "ls -la nginx/templates/tiktok.flowbiz.cloud.conf.template"

echo ""
echo "================================================================"
echo "STEP 3: Provision SSL certificate for subdomain"
echo "================================================================"
echo "Run one of the following commands:"
echo ""
echo "Option A (recommended - nginx plugin):"
echo "  sudo certbot certonly --nginx -d tiktok.flowbiz.cloud"
echo ""
echo "Option B (webroot):"
echo "  sudo certbot certonly --webroot -w /var/www/certbot -d tiktok.flowbiz.cloud"
echo ""
echo "Follow certbot prompts to complete certificate provisioning"

echo ""
echo "================================================================"
echo "STEP 4: Verify certificate was created"
echo "================================================================"
echo "Run: sudo ls -la /etc/letsencrypt/live/tiktok.flowbiz.cloud/"
echo "Expected files: fullchain.pem, privkey.pem, cert.pem, chain.pem"

echo ""
echo "================================================================"
echo "STEP 5: Install vhost into system nginx"
echo "================================================================"
echo "sudo cp nginx/templates/tiktok.flowbiz.cloud.conf.template /etc/nginx/conf.d/tiktok.flowbiz.cloud.conf"

echo ""
echo "================================================================"
echo "STEP 6: Validate + reload system nginx"
echo "================================================================"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"

echo ""
echo "================================================================"
echo "STEP 7: Verify system nginx is running"
echo "================================================================"
echo "sudo systemctl status nginx --no-pager"

echo ""
echo "================================================================"
echo "STEP 8: Test routing - HTTP redirect"
echo "================================================================"
echo "curl -I http://tiktok.flowbiz.cloud/healthz"
echo "Expected: 301 Moved Permanently"

echo ""
echo "================================================================"
echo "STEP 9: Test routing - HTTPS health check"
echo "================================================================"
echo "curl -fsS https://tiktok.flowbiz.cloud/healthz"
echo "Expected: {\"status\":\"ok\",...}"

echo ""
echo "================================================================"
echo "STEP 10: Test routing - Metadata endpoint"
echo "================================================================"
echo "curl -fsS https://tiktok.flowbiz.cloud/v1/meta"
echo "Expected: Service metadata JSON"

echo ""
echo "================================================================"
echo "STEP 11: Test routing - Analytics endpoint"
echo "================================================================"
echo "curl -fsS https://tiktok.flowbiz.cloud/v1/analytics/summary"
echo "Expected: Analytics data JSON (or error if no data yet)"

echo ""
echo "================================================================"
echo "STEP 12: Test routing - Reliability endpoint"
echo "================================================================"
echo "curl -fsS https://tiktok.flowbiz.cloud/v1/reliability/summary"
echo "Expected: Reliability data JSON (or error if no data yet)"

echo ""
echo "================================================================"
echo "STEP 13: Verify security headers"
echo "================================================================"
echo "curl -I https://tiktok.flowbiz.cloud/healthz"
echo "Expected headers:"
echo "  - Strict-Transport-Security: max-age=63072000; includeSubDomains; preload"
echo "  - X-Content-Type-Options: nosniff"
echo "  - X-Frame-Options: DENY"
echo "  - Referrer-Policy: strict-origin-when-cross-origin"
echo "  - Permissions-Policy: geolocation=(), microphone=(), camera=()"

echo ""
echo "================================================================"
echo "DEPLOYMENT COMPLETE"
echo "================================================================"
echo "TikTok API is now available at: https://tiktok.flowbiz.cloud"
echo "Dashboard remains private (SSH port-forward): 127.0.0.1:3002"
echo ""
echo "To access dashboard from local machine:"
echo "  ssh -L 3002:127.0.0.1:3002 flowbiz-vps"
echo "  Then open: http://localhost:3002"
echo ""
echo "================================================================"

echo ""
echo "================================================================"
echo "ROLLBACK PROCEDURE (if needed)"
echo "================================================================"
echo "If deployment causes issues, run:"
echo ""
echo "# Option 1: Disable template"
echo "sudo mv /etc/nginx/conf.d/tiktok.flowbiz.cloud.conf /etc/nginx/conf.d/tiktok.flowbiz.cloud.conf.disabled"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# Option 2: Revert git commit"
echo "git log --oneline -5  # Find commit SHA"
echo "git revert <commit-sha>"
echo "docker compose up -d --build --remove-orphans"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# Verify core services"
echo "curl https://flowbiz.cloud/healthz"
echo "================================================================"
